apiVersion: v1
kind: Pod
metadata:
  name: victim
  namespace: default
spec:
  containers:
  - name: victim
    image: python:3.9-slim
    # We need this to keep the container running
    command: ["sleep", "infinity"]
    ports:
    - containerPort: 9100
      name: metrics
    env:
    - name: SECRET_API_KEY
      value: "super-secret-key-12345"
