apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vuln-test-role
rules:
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vuln-test-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vuln-test-binding
subjects:
- kind: ServiceAccount
  name: vuln-test-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: vuln-test-role
  apiGroup: rbac.authorization.k8s.io
