apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-dev
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-binding
subjects:
- kind: ServiceAccount
  name: monitor-dev
  namespace: default
roleRef:
  kind: ClusterRole
  name: monitor-role
  apiGroup: rbac.authorization.k8s.io
